# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doviz.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from bs4 import BeautifulSoup
import requests

class KurAl:
    def __init__(self, url):
        self.url = url

    def kur_getir(self):
        sayfa = requests.get(self.url)
        html_sayfa = BeautifulSoup(sayfa.content, "html.parser")
        kur = html_sayfa.find("div", class_="YMlKec fxKbKc").getText()
        return kur

class Ui_DovizCevirici(object):
    def setupUi(self, DovizCevirici):
        DovizCevirici.setObjectName("DovizCevirici")
        DovizCevirici.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(DovizCevirici)
        self.centralwidget.setObjectName("centralwidget")
        self.tlKarsilik = QtWidgets.QLabel(self.centralwidget)
        self.tlKarsilik.setGeometry(QtCore.QRect(210, 120, 150, 16))
        self.tlKarsilik.setObjectName("tlKarsilik")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 160, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(110, 120, 73, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 0, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        DovizCevirici.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DovizCevirici)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        DovizCevirici.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DovizCevirici)
        self.statusbar.setObjectName("statusbar")
        DovizCevirici.setStatusBar(self.statusbar)

        self.retranslateUi(DovizCevirici)
        QtCore.QMetaObject.connectSlotsByName(DovizCevirici)

        # Event handling
        self.pushButton.clicked.connect(self.doviz_cevir)

        # İlk başta dolar kuru gösterilsin
        self.ilk_kur_goster()

    def retranslateUi(self, DovizCevirici):
        _translate = QtCore.QCoreApplication.translate
        DovizCevirici.setWindowTitle(_translate("DovizCevirici", "Döviz Çevirici"))
        self.pushButton.setText(_translate("DovizCevirici", "TL'ye çevir"))
        self.comboBox.setCurrentText(_translate("DovizCevirici", "Dolar"))
        self.comboBox.setItemText(0, _translate("DovizCevirici", "Dolar"))
        self.comboBox.setItemText(1, _translate("DovizCevirici", "Euro"))
        self.comboBox.setItemText(2, _translate("DovizCevirici", "Pound"))
        self.label_2.setText(_translate("DovizCevirici", "DÖVİZ ÇEVİRİCİ"))

    def ilk_kur_goster(self):
        dolar_url = "https://www.google.com/finance/quote/USD-TRY?hl=tr"
        kur_al = KurAl(dolar_url)
        kur = kur_al.kur_getir()
        self.tlKarsilik.setText(kur)

    def doviz_cevir(self):
        doviz_turu = self.comboBox.currentText()
        if doviz_turu == "Dolar":
            url = "https://www.google.com/finance/quote/USD-TRY?hl=tr"
        elif doviz_turu == "Euro":
            url = "https://www.google.com/finance/quote/EUR-TRY?hl=tr"
        elif doviz_turu == "Pound":
            url = "https://www.google.com/finance/quote/GBP-TRY?hl=tr"
        else:
            url = ""

        if url:
            kur_al = KurAl(url)
            kur = kur_al.kur_getir()
            self.tlKarsilik.setText(kur)

def main():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DovizCevirici = QtWidgets.QMainWindow()
    ui = Ui_DovizCevirici()
    ui.setupUi(DovizCevirici)
    DovizCevirici.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
